SPA_FRONTEND_ROUTES = {
    "/",
    "/about",
    "/kerko",
    "/bizneset",
    "/profili-biznesit",
    "/mesazhet",
    "/njoftimet",
    "/login",
    "/forgot-password",
    "/signup",
    "/verifiko-email",
    "/biznesi-juaj",
    "/llogaria",
    "/te-dhenat-personale",
    "/adresat",
    "/porosite",
    "/payments",
    "/support",
    "/track-order",
    "/porosite-e-biznesit",
    "/refund-returne",
    "/admin-porosite",
    "/ndrysho-fjalekalimin",
    "/produkti",
    "/wishlist",
    "/cart",
    "/adresa-e-porosise",
    "/menyra-e-pageses",
    "/porosia-u-konfirmua",
    "/kafshet-shtepiake",
    "/admin-products",
    "/admin-products/inventory",
    "/admin-products/lista",
    "/admin-users",
    "/admin-disputes",
    "/admin-categories",
    "/admin-commissions",
    "/admin-payouts",
    "/bizneset-e-regjistruara",
    "/krahaso-produkte",
    "/liquid-glass",
}

LEGACY_PAGE_ROUTES = {
    "/": "/legacy/index.html",
    "/about": "/legacy/about.html",
    "/kerko": "/legacy/search.html",
    "/profili-biznesit": "/legacy/business-profile-public.html",
    "/mesazhet": "/legacy/messages.html",
    "/njoftimet": "/legacy/account.html",
    "/login": "/legacy/login.html",
    "/forgot-password": "/legacy/forgot-password.html",
    "/signup": "/legacy/signup.html",
    "/verifiko-email": "/legacy/verify-email.html",
    "/biznesi-juaj": "/legacy/index.html",
    "/llogaria": "/legacy/account.html",
    "/te-dhenat-personale": "/legacy/personal-data.html",
    "/adresat": "/legacy/addresses.html",
    "/porosite": "/legacy/orders.html",
    "/track-order": "/legacy/orders.html",
    "/porosite-e-biznesit": "/legacy/business-orders.html",
    "/ndrysho-fjalekalimin": "/legacy/change-password.html",
    "/produkti": "/legacy/product-detail.html",
    "/wishlist": "/legacy/wishlist.html",
    "/cart": "/legacy/cart.html",
    "/adresa-e-porosise": "/legacy/checkout-address.html",
    "/menyra-e-pageses": "/legacy/payment-options.html",
    "/kafshet-shtepiake": "/legacy/pets.html",
    "/admin-products": "/legacy/index.html",
    "/bizneset-e-regjistruara": "/legacy/registered-businesses.html",
}

ADMIN_PAGE_ROUTES = {"/admin-products", "/bizneset-e-regjistruara"}
BUSINESS_PAGE_ROUTES = {"/biznesi-juaj", "/porosite-e-biznesit"}
CHAT_PAGE_ROUTE = "/mesazhet"
AUTHENTICATED_PAGE_ROUTES = {
    "/llogaria",
    "/te-dhenat-personale",
    "/adresat",
    "/adresa-e-porosise",
    "/menyra-e-pageses",
    "/porosite",
    "/njoftimet",
    "/ndrysho-fjalekalimin",
}
PASSWORD_RESET_ROUTE = "/ndrysho-fjalekalimin"

GET_API_ROUTES = {
    "/api/chat/unread-reminders": ("handle_chat_unread_reminders", False),
    "/api/stats": ("handle_stats", False),
    "/api/me": ("handle_me", False),
    "/api/admin/users": ("handle_admin_users_list", False),
    "/api/admin/businesses": ("handle_admin_businesses_list", False),
    "/api/businesses/public": ("handle_public_businesses_list", False),
    "/api/search/autocomplete": ("handle_search_autocomplete", True),
    "/api/address": ("handle_default_address", False),
    "/api/business-profile": ("handle_business_profile", False),
    "/api/launch-ads": ("handle_launch_ads_list", False),
    "/api/business/products": ("handle_business_products_list", False),
    "/api/business/products/import-template": ("handle_business_products_import_template", False),
    "/api/business/catalog-import/config": ("handle_business_catalog_import_config", False),
    "/api/business/public": ("handle_public_business_detail", True),
    "/api/business/public-products": ("handle_public_business_products", True),
    "/api/chat/conversations": ("handle_chat_conversations", False),
    "/api/chat/messages": ("handle_chat_messages", True),
    "/api/chat/reply-suggestions": ("handle_chat_reply_suggestions", True),
    "/api/products/search": ("handle_products_search", True),
    "/api/recommendations/home": ("handle_home_recommendations", True),
    "/api/recommendations/product": ("handle_product_recommendations", True),
    "/api/product": ("handle_product_detail", True),
    "/api/product/reviews": ("handle_product_reviews_list", True),
    "/api/products": ("handle_products_list", True),
    "/api/admin/products": ("handle_admin_products_list", False),
    "/api/wishlist": ("handle_wishlist", False),
    "/api/cart": ("handle_cart", False),
    "/api/orders": ("handle_orders_list", False),
    "/api/orders/invoice": ("handle_order_invoice", True),
    "/api/business/orders": ("handle_business_orders_list", True),
    "/api/business/analytics": ("handle_business_analytics", False),
    "/api/business/promotions": ("handle_business_promotions_list", False),
    "/api/admin/orders": ("handle_admin_orders_list", True),
    "/api/admin/reports": ("handle_admin_reports_list", False),
    "/api/admin/launch-ads": ("handle_admin_launch_ads_list", False),
    "/api/returns": ("handle_returns_list", False),
    "/api/notifications": ("handle_notifications_list", False),
    "/api/notifications/count": ("handle_notifications_count", False),
    "/api/push/public-key": ("handle_push_public_key", False),
    "/api/whatsapp/webhook": ("handle_whatsapp_webhook_verify", True),
}

POST_API_ROUTES = {
    "/api/register": "handle_register",
    "/api/login": "handle_login",
    "/api/auth/google": "handle_google_auth",
    "/api/email/verify": "handle_email_verification",
    "/api/email/resend": "handle_email_verification_resend",
    "/api/forgot-password": "handle_forgot_password",
    "/api/password-reset/confirm": "handle_password_reset_confirm",
    "/api/logout": "handle_logout",
    "/api/change-password": "handle_change_password",
    "/api/profile": "handle_profile_update",
    "/api/profile/photo": "handle_profile_photo_upload",
    "/api/account/delete": "handle_delete_own_account",
    "/api/address": "handle_save_default_address",
    "/api/address/geocode": "handle_reverse_geocode_address",
    "/api/business-profile": "handle_save_business_profile",
    "/api/business-profile/auto-reply": "handle_save_business_auto_reply_settings",
    "/api/business-profile/shipping": "handle_save_business_shipping_settings",
    "/api/business-profile/verification-request": "handle_business_verification_request",
    "/api/business-profile/edit-request": "handle_business_profile_edit_request",
    "/api/admin/users/role": "handle_admin_user_role",
    "/api/admin/users/delete": "handle_admin_delete_user",
    "/api/admin/users/set-password": "handle_admin_set_user_password",
    "/api/admin/businesses/create": "handle_admin_create_business_account",
    "/api/admin/businesses/update": "handle_admin_update_business",
    "/api/admin/businesses/verification": "handle_admin_update_business_verification",
    "/api/admin/businesses/edit-access": "handle_admin_update_business_edit_access",
    "/api/admin/businesses/logo": "handle_admin_update_business_logo",
    "/api/admin/launch-ads": "handle_save_admin_launch_ad",
    "/api/uploads": "handle_image_uploads",
    "/api/products/visual-search": "handle_products_visual_search",
    "/api/products/ai-draft": "handle_product_ai_draft",
    "/api/products/ai-description": "handle_product_ai_description",
    "/api/products/ai-tag-suggestions": "handle_product_ai_tag_suggestions",
    "/api/products/share": "handle_product_share",
    "/api/products": "handle_create_product",
    "/api/products/update": "handle_update_product",
    "/api/products/delete": "handle_delete_product",
    "/api/products/public-visibility": "handle_product_public_visibility",
    "/api/products/public-stock": "handle_product_public_stock",
    "/api/products/restock": "handle_restock_product",
    "/api/products/reduce-stock": "handle_reduce_stock_product",
    "/api/business/products/import": "handle_business_products_import",
    "/api/business/catalog-import/preview": "handle_business_catalog_import_preview",
    "/api/business/catalog-import/commit": "handle_business_catalog_import_commit",
    "/api/business/catalog-import/profile": "handle_business_catalog_import_profile_save",
    "/api/business/catalog-import/source": "handle_business_catalog_import_source_save",
    "/api/business/catalog-import/sync": "handle_business_catalog_import_sync",
    "/api/chat/open": "handle_chat_open",
    "/api/chat/typing": "handle_chat_typing",
    "/api/chat/messages": "handle_chat_send_message",
    "/api/chat/messages/update": "handle_chat_update_message",
    "/api/chat/messages/delete": "handle_chat_delete_message",
    "/api/payments/stripe/checkout": "handle_create_stripe_checkout_session",
    "/api/payments/stripe/confirm": "handle_confirm_stripe_checkout_session",
    "/api/wishlist/toggle": "handle_toggle_wishlist",
    "/api/cart/add": "handle_add_to_cart",
    "/api/cart/quantity": "handle_update_cart_quantity",
    "/api/cart/remove": "handle_remove_from_cart",
    "/api/checkout/reserve": "handle_checkout_reserve_stock",
    "/api/business/follow-toggle": "handle_business_follow_toggle",
    "/api/promotions/apply": "handle_apply_promotion",
    "/api/business/promotions": "handle_save_business_promotion",
    "/api/orders/create": "handle_create_order",
    "/api/orders/track": "handle_track_order_lookup",
    "/api/orders/status": "handle_update_order_status",
    "/api/reports": "handle_create_report",
    "/api/admin/reports/status": "handle_admin_update_report_status",
    "/api/product/reviews": "handle_create_product_review",
    "/api/returns/request": "handle_create_return_request",
    "/api/returns/status": "handle_update_return_request_status",
    "/api/notifications/read": "handle_mark_notifications_read",
    "/api/push/subscribe": "handle_push_subscribe",
    "/api/push/unsubscribe": "handle_push_unsubscribe",
    "/api/push/test": "handle_push_test",
    "/api/send-notification": "handle_send_notification",
    "/send-notification": "handle_send_notification",
    "/api/whatsapp/webhook": "handle_whatsapp_webhook_event",
}


def build_page_routes(frontend_dist_exists: bool) -> dict[str, str]:
    if frontend_dist_exists:
        return {route: "/index.html" for route in SPA_FRONTEND_ROUTES}
    return LEGACY_PAGE_ROUTES
